#!/bin/bash
# Preflight script for Time Machine Scheduler package.
# Need to create log files/log destination.

# check for Log directory
DIRECTORY="/Library/Logs/com.trmacs/"

if [ -d "$DIRECTORY" ]; then

	echo ""$Directory" exists, no need to create it."

else
	echo "Log directory does not exist, creating /Library/Logs/com.trmacs/"
	mkdir -p /Library/Logs/com.trmacs/
	echo "done"
fi

# Checks to see if the launchd is loaded, and if not null (-n), then unload it.
launchd_chk="$(launchctl list | grep trmacs.backupd-auto)"

echo "checking for previously loaded plist."

if [ -n "$launchd_chk" ]; then

	echo "previous version found, unloading"
	launchctl unload -w /Library/LaunchDaemons/com.trmacs.backupd-auto.plist
	echo "done"
else
	echo "No previous version found, nothing to unload."
fi

echo "exiting"

exit 0