#!/bin/sh
## postflight

pathToScript=$0
pathToPackage=$1
targetLocation=$2
targetVolume=$3

launchctl load -w /Library/LaunchDaemons/com.trmacs.backupd-auto.plist

exit 0		## Success
exit 1		## Failure
