#!/bin/bash
# loads the just installed launchdaemon. If previously loaded, was unloaded in Preflight.
vers="applehwraidSMARTcheck_postflight_v0.2

echo "$vers"
echo "loading /Library/LaunchDaemons/com.trmacs.applehwsmartcheck.plist"
launchctl load /Library/LaunchDaemons/com.trmacs.applehwsmartcheck.plist
echo "done"
echo "exiting"

exit 0